# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11" # Or your desired Python version
  jobs:
    post_checkout:
      # Fetch all history and tags for setuptools-scm
      - git fetch --unshallow || git fetch --depth=20000 # Deeper fallback if unshallow fails
      - git fetch --tags

python:
  install:
    - requirements: docs/src/requirements.txt
    # If your project itself needs to be installed for docs:
    - method: pip
      path: .
      # extra_requirements:
      #   - docs

sphinx:
  configuration: docs/src/conf.py